// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

using System.Reflection;
using System.Web;

namespace Pidgeon.Core.Application.Services.Reporting;

/// <summary>
/// Renders the shared attribution footer for shareable HTML reports: the generating
/// Pidgeon version, a pidgeon.health link carrying a ref param that identifies the
/// artifact kind (the web-lane attribution shape from SHAREABLE_RUN_STANDARD.md §8),
/// and, when the report came from a reproducible invocation, the one-line reproduce
/// command. Static text plus one anchor only — no scripts, no tracking pixels.
/// </summary>
public static class ReportAttribution
{
    /// <summary>Version stamped into report footers: the hosting binary's informational version without build metadata.</summary>
    public static string Version { get; } = ResolveVersion();

    /// <summary>
    /// Builds the footer HTML for a report.
    /// </summary>
    /// <param name="artifactKind">Ref-param value identifying the artifact kind (e.g. "report-diff", "report-validate").</param>
    /// <param name="reproduceCommand">Optional one-line CLI command that reproduces the report.</param>
    public static string FooterHtml(string artifactKind, string? reproduceCommand = null)
    {
        var link = $"https://pidgeon.health/?ref={Uri.EscapeDataString(artifactKind)}";
        var reproduce = string.IsNullOrWhiteSpace(reproduceCommand)
            ? string.Empty
            : $"\n<p>Reproduce: <code>{HttpUtility.HtmlEncode(reproduceCommand)}</code></p>";

        return
            "<div class=\"attribution\" style=\"text-align:center;padding:16px 0;color:#a0aec0;font-size:12px;\">\n" +
            $"<p>Generated by Pidgeon v{HttpUtility.HtmlEncode(Version)} · " +
            $"<a href=\"{link}\" style=\"color:#a0aec0;\">pidgeon.health</a></p>{reproduce}\n" +
            "</div>";
    }

    private static string ResolveVersion()
    {
        var informational = (Assembly.GetEntryAssembly() ?? typeof(ReportAttribution).Assembly)
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        if (string.IsNullOrWhiteSpace(informational))
            return "dev";

        // Strip "+<commit>" build metadata; the footer shows the human-facing version only.
        var metadataStart = informational.IndexOf('+');
        return metadataStart > 0 ? informational[..metadataStart] : informational;
    }
}
